// Small utility used by the WIRE-0 external-Action proof PR.
// Deliberately real code (not a docs-only change) so the pr-walkthrough
// pipeline has an actual diff to parse, cluster, and risk-assess.

export function buildGreeting(name) {
  if (typeof name !== 'string' || !name.trim()) {
    throw new Error('buildGreeting: name must be a non-empty string');
  }
  return `Hello, ${name.trim()}! This walkthrough was generated by the public opensoyce-pr-walkthrough-action.`;
}

export function shout(text) {
  return String(text).toUpperCase() + '!!!';
}
